### ISSUE TITLE
film duration should have values only between 60-240

### ISSUE THREAD

**Issue by Japoivvb** [Omirzar1337/oriol_miralles_uf3_p1#1]
1. please update logic to insert data in specific range to avoid strange durations in our reports about movies by minutes

2. create a hotfix branch to fix it

3. set label as bug to be tracked

4. commit message with #numberIssue verb(in 3rd person) +  details
 
5. create pull request and merge to main branch mention me with @name when it is ready in order to close issue please

**Comment by Omirzar1337** [comment]
Sure, I'll fix it ASAP.

**Comment by Omirzar1337** [comment]
Isn't that how I already addressed the problem? FilmFakerSeeder.php:21

![image](https://github.com/Omirzar1337/oriol_miralles_uf3_p1/assets/65012775/0ddc2af8-76a1-422c-b5d0-293ec2778dcc)

**Comment by Japoivvb** [comment]
you are right, issue close as rejected
